import { Inter } from "next/font/google";
import "./globals.css";
import "./normalize.css";
import Header from "./components/Header/header";
import { MotionProvider } from "./MotionContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <MotionProvider>
        <body className={inter.className}>
          <Header />
          {children}
        </body>
      </MotionProvider>
    </html>
  );
}
